name: tests
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: npx jest